### ISSUE TITLE
Doesn't work well with mix

### ISSUE THREAD

**Issue by Linuus** [alertlogic/erlcloud#105]
When switching from the main erlcloud repo to this fork I got problems with dependencies that was impossible to resolve.

```
Unchecked dependencies for environment dev:
* jsx (git://github.com/talentdeficit/jsx.git)
  lock outdated: the lock is outdated compared to the options in your mixfile (run "mix deps.get" to fetch locked version)
** (Mix) Can't continue due to errors on dependencies
```

After some conversation on the #elixir-lang irc channel it was found that this check is broken in mix:
https://github.com/alertlogic/erlcloud/blob/master/rebar.config.script#L13

I had to add: `{:jsx, "~> 2.5", override: true}` to my dependencies to make it work.

**Comment by motobob** [comment]
this is strange as `rebar3` & `mix` support is identical between forks.

**Comment by Linuus** [comment]
Ok. Maybe @ericmj can give some more information about what should be done to fix this?

**Comment by ericmj** [comment]
The problem is that you only use hex dependencies when rebar3 loads rebar.config.script, but mix (1.2.0+) will also load this file and then the `erlang:function_exported(rebar3, main, 1)` check fails.

Flipping it to check for rebar2 instead would handle both rebar3 and mix in the `false` case.

**Comment by motobob** [comment]
that was all adressed in upstream as we merge AL fork there. 
please fee free to reopen if still a problem.
