### ISSUE TITLE
"aws request" code redundancy in multiple modules

### ISSUE THREAD

**Issue by KingBrewer** [alertlogic/erlcloud#123]
Many erlcloud modules re-implement big part of the "aws request", probably for the purpose of setting custom http headers (especially when they want to enforce JSON output on AWS API).

Example: [here](https://github.com/alertlogic/erlcloud/blob/master/src/erlcloud_cloudtrail.erl#L174-L208).

I propose to extend `erlcloud_aws:aws_request4()` function so that headers could be passed as additional parameter, eliminating the necessity of re-implementing headers signing part.
Respective PR is underway.

**Comment by nalundgaard** [comment]
seems like, if that is needed, it should be done in erlcloud/erlcloud and then merged back in here.

**Comment by KingBrewer** [comment]
@nalundgaard it will eventually become the dependency of cloudsearch implementation. So I'd prefer to keep it here. But I'm open to any option.
