### ISSUE TITLE
Sigv2 removal?

### ISSUE THREAD

**Issue by motobob** [alertlogic/erlcloud#126]
Dear `alertlogic/erlcloud` consumers,
any objections to remove SigV2 signing and leaving only Sigv4? 

http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html
Currently all services support SigV4, expect AWS Simple DB which supports only Sigv2. So  suggestion to move it there and simplify `erlcloud_aws.erl` module?

BTW: it looks like SBD is [broken](https://github.com/alertlogic/erlcloud/blob/master/src/erlcloud_sdb.erl#L367) in AL fork and not [upstream](https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_sdb.erl#L367) clearly showing nobody's using it.

**Comment by kkuzmin** [comment]
+1 for SignV4 only.

**Comment by motobob** [comment]
question answered. roadmap item in upstream
