### ISSUE TITLE
DEFAULT_TIMEOUT defined in public header

### ISSUE THREAD

**Issue by hmartel-alertlogic** [alertlogic/erlcloud#99]
https://github.com/alertlogic/erlcloud/blob/master/include/erlcloud_aws.hrl#L90 defines `DEFAULT_TIMEOUT` which is an extremely non-specific name for a public include, and as a result, breaks other modules dependent on this one.

**Comment by motobob** [comment]
true... a PR is welcome if that is urgent, otherwise we will fix that with next release

**Comment by motobob** [comment]
addressed
